[project]
name = "md2do"
version = "0.1.0"
description = "Speech-to-LLM todo.md updater"
requires-python = ">=3.8"
dependencies = [
    "speechrecognition",
    "pyaudio",
    "transformers",
    "torch",
    "ollama"
]

[tool.uv] 
